'use strict';

const assert = require('assert');
const {
  parsePackageLock,
  parseYarnLock,
  parsePnpmLock,
  diffLockfiles,
  detectFormat,
  parseLockfile,
  classifyVersionChange,
  computeStats,
  extractPkgName,
  extractYarnPkgName,
} = require('../src/index');

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    passed++;
    process.stdout.write('.');
  } catch (err) {
    failed++;
    process.stdout.write('F');
    console.error(`\n✗ ${name}: ${err.message}`);
  }
}

// ── extractPkgName ──────────────────────────────────────

test('extractPkgName: simple package', () => {
  assert.strictEqual(extractPkgName('node_modules/lodash'), 'lodash');
});

test('extractPkgName: scoped package', () => {
  assert.strictEqual(extractPkgName('node_modules/@scope/foo'), '@scope/foo');
});

test('extractPkgName: nested node_modules', () => {
  assert.strictEqual(extractPkgName('node_modules/a/node_modules/b'), 'b');
});

test('extractPkgName: deeply nested scoped', () => {
  assert.strictEqual(extractPkgName('node_modules/x/node_modules/@scope/y'), '@scope/y');
});

// ── extractYarnPkgName ──────────────────────────────────

test('extractYarnPkgName: simple', () => {
  assert.strictEqual(extractYarnPkgName('lodash@^4.17.0'), 'lodash');
});

test('extractYarnPkgName: scoped', () => {
  assert.strictEqual(extractYarnPkgName('@scope/foo@^1.0.0'), '@scope/foo');
});

test('extractYarnPkgName: scoped with npm protocol', () => {
  assert.strictEqual(extractYarnPkgName('@scope/foo@npm:^1.0.0'), '@scope/foo');
});

test('extractYarnPkgName: no range', () => {
  assert.strictEqual(extractYarnPkgName('@scope/foo'), '@scope/foo');
});

// ── parsePackageLock (v2/v3) ────────────────────────────

test('parsePackageLock: v3 basic', () => {
  const lock = JSON.stringify({
    lockfileVersion: 3,
    packages: {
      '': { version: '1.0.0' },
      'node_modules/lodash': { version: '4.17.21' },
      'node_modules/express': { version: '4.18.2' },
    },
  });
  const pkgs = parsePackageLock(lock);
  assert.strictEqual(pkgs.size, 2);
  assert.strictEqual(pkgs.get('lodash').version, '4.17.21');
  assert.strictEqual(pkgs.get('express').version, '4.18.2');
});

test('parsePackageLock: v3 scoped package', () => {
  const lock = JSON.stringify({
    lockfileVersion: 3,
    packages: {
      '': { version: '1.0.0' },
      'node_modules/@babel/core': { version: '7.20.0' },
    },
  });
  const pkgs = parsePackageLock(lock);
  assert.strictEqual(pkgs.get('@babel/core').version, '7.20.0');
});

test('parsePackageLock: v3 nested dedupes to first', () => {
  const lock = JSON.stringify({
    lockfileVersion: 3,
    packages: {
      '': {},
      'node_modules/foo': { version: '1.0.0' },
      'node_modules/bar/node_modules/foo': { version: '2.0.0' },
    },
  });
  const pkgs = parsePackageLock(lock);
  assert.strictEqual(pkgs.get('foo').version, '1.0.0');
});

test('parsePackageLock: v3 skips root', () => {
  const lock = JSON.stringify({
    lockfileVersion: 3,
    packages: {
      '': { version: '1.0.0', name: 'myapp' },
      'node_modules/lodash': { version: '4.17.21' },
    },
  });
  const pkgs = parsePackageLock(lock);
  assert.strictEqual(pkgs.size, 1);
  assert.ok(!pkgs.has('myapp'));
});

test('parsePackageLock: v1 format (dependencies)', () => {
  const lock = JSON.stringify({
    lockfileVersion: 1,
    dependencies: {
      lodash: { version: '4.17.21' },
      express: { version: '4.18.2' },
    },
  });
  const pkgs = parsePackageLock(lock);
  assert.strictEqual(pkgs.size, 2);
  assert.strictEqual(pkgs.get('lodash').version, '4.17.21');
});

test('parsePackageLock: v1 nested dependencies', () => {
  const lock = JSON.stringify({
    lockfileVersion: 1,
    dependencies: {
      foo: {
        version: '1.0.0',
        dependencies: {
          bar: { version: '2.0.0' },
        },
      },
    },
  });
  const pkgs = parsePackageLock(lock);
  assert.strictEqual(pkgs.get('foo').version, '1.0.0');
  assert.strictEqual(pkgs.get('bar').version, '2.0.0');
});

test('parsePackageLock: throws on unrecognized format', () => {
  assert.throws(() => parsePackageLock('{}'), /Unrecognized/);
});

// ── parseYarnLock ───────────────────────────────────────

test('parseYarnLock: basic single entry', () => {
  const content = `# THIS IS AN AUTOGENERATED FILE

lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
`;
  const pkgs = parseYarnLock(content);
  assert.strictEqual(pkgs.get('lodash').version, '4.17.21');
});

test('parseYarnLock: scoped package', () => {
  const content = `"@babel/core@^7.0.0":
  version "7.20.0"
  resolved "..."
`;
  const pkgs = parseYarnLock(content);
  assert.strictEqual(pkgs.get('@babel/core').version, '7.20.0');
});

test('parseYarnLock: multiple entries', () => {
  const content = `lodash@^4.17.0:
  version "4.17.21"

express@^4.18.0:
  version "4.18.2"
`;
  const pkgs = parseYarnLock(content);
  assert.strictEqual(pkgs.size, 2);
  assert.strictEqual(pkgs.get('lodash').version, '4.17.21');
  assert.strictEqual(pkgs.get('express').version, '4.18.2');
});

test('parseYarnLock: multiple ranges for same pkg', () => {
  const content = `"lodash@^4.17.0, lodash@^4.0.0":
  version "4.17.21"
`;
  const pkgs = parseYarnLock(content);
  assert.strictEqual(pkgs.get('lodash').version, '4.17.21');
});

test('parseYarnLock: dedupes to first occurrence', () => {
  const content = `lodash@^4.17.0:
  version "4.17.21"

lodash@^3.0.0:
  version "3.10.1"
`;
  const pkgs = parseYarnLock(content);
  assert.strictEqual(pkgs.get('lodash').version, '4.17.21');
});

// ── parsePnpmLock ───────────────────────────────────────

test('parsePnpmLock: basic packages', () => {
  const content = `lockfileVersion: '9.0'

packages:

  /lodash@4.17.21:
    resolution: {tarball: '...'}

  /express@4.18.2:
    resolution: {tarball: '...'}
`;
  const pkgs = parsePnpmLock(content);
  assert.strictEqual(pkgs.get('lodash').version, '4.17.21');
  assert.strictEqual(pkgs.get('express').version, '4.18.2');
});

test('parsePnpmLock: scoped package', () => {
  const content = `lockfileVersion: '9.0'

packages:

  /@babel/core@7.20.0:
    resolution: {tarball: '...'}
`;
  const pkgs = parsePnpmLock(content);
  assert.strictEqual(pkgs.get('@babel/core').version, '7.20.0');
});

test('parsePnpmLock: ignores non-packages sections', () => {
  const content = `lockfileVersion: '9.0'

dependencies:
  lodash: 4.17.21

packages:

  /lodash@4.17.21:
    resolution: {tarball: '...'}

snapshots:
  lodash: {}
`;
  const pkgs = parsePnpmLock(content);
  assert.strictEqual(pkgs.size, 1);
  assert.strictEqual(pkgs.get('lodash').version, '4.17.21');
});

// ── detectFormat ────────────────────────────────────────

test('detectFormat: by filename npm', () => {
  assert.strictEqual(detectFormat('package-lock.json'), 'npm');
});

test('detectFormat: by filename yarn', () => {
  assert.strictEqual(detectFormat('yarn.lock'), 'yarn');
});

test('detectFormat: by filename pnpm', () => {
  assert.strictEqual(detectFormat('pnpm-lock.yaml'), 'pnpm');
});

test('detectFormat: by content npm', () => {
  const content = JSON.stringify({ lockfileVersion: 3, packages: {} });
  assert.strictEqual(detectFormat('unknown.txt', content), 'npm');
});

test('detectFormat: by content yarn', () => {
  const content = '# THIS IS AN AUTOGENERATED FILE...\nyarn lockfile';
  assert.strictEqual(detectFormat('unknown.txt', content), 'yarn');
});

test('detectFormat: unknown returns null', () => {
  assert.strictEqual(detectFormat('foo.txt', 'hello world'), null);
});

// ── parseLockfile dispatch ──────────────────────────────

test('parseLockfile: npm dispatch', () => {
  const content = JSON.stringify({
    lockfileVersion: 3,
    packages: { 'node_modules/foo': { version: '1.0.0' } },
  });
  const pkgs = parseLockfile(content, 'npm');
  assert.strictEqual(pkgs.get('foo').version, '1.0.0');
});

test('parseLockfile: unknown format throws', () => {
  assert.throws(() => parseLockfile('', 'wut'), /Unknown/);
});

// ── diffLockfiles ───────────────────────────────────────

test('diffLockfiles: added packages', () => {
  const before = new Map([['lodash', { version: '4.17.0' }]]);
  const after = new Map([
    ['lodash', { version: '4.17.0' }],
    ['express', { version: '4.18.0' }],
  ]);
  const diff = diffLockfiles(before, after);
  assert.strictEqual(diff.added.length, 1);
  assert.strictEqual(diff.added[0].name, 'express');
  assert.strictEqual(diff.removed.length, 0);
  assert.strictEqual(diff.changed.length, 0);
});

test('diffLockfiles: removed packages', () => {
  const before = new Map([
    ['lodash', { version: '4.17.0' }],
    ['express', { version: '4.18.0' }],
  ]);
  const after = new Map([['lodash', { version: '4.17.0' }]]);
  const diff = diffLockfiles(before, after);
  assert.strictEqual(diff.removed.length, 1);
  assert.strictEqual(diff.removed[0].name, 'express');
});

test('diffLockfiles: changed versions', () => {
  const before = new Map([['lodash', { version: '4.17.0' }]]);
  const after = new Map([['lodash', { version: '4.17.21' }]]);
  const diff = diffLockfiles(before, after);
  assert.strictEqual(diff.changed.length, 1);
  assert.strictEqual(diff.changed[0].before, '4.17.0');
  assert.strictEqual(diff.changed[0].after, '4.17.21');
});

test('diffLockfiles: unchanged packages', () => {
  const before = new Map([['lodash', { version: '4.17.0' }]]);
  const after = new Map([['lodash', { version: '4.17.0' }]]);
  const diff = diffLockfiles(before, after);
  assert.strictEqual(diff.unchanged.length, 1);
  assert.strictEqual(diff.added.length, 0);
  assert.strictEqual(diff.removed.length, 0);
  assert.strictEqual(diff.changed.length, 0);
});

test('diffLockfiles: mixed changes', () => {
  const before = new Map([
    ['a', { version: '1.0.0' }],
    ['b', { version: '2.0.0' }],
    ['c', { version: '3.0.0' }],
  ]);
  const after = new Map([
    ['a', { version: '1.1.0' }],
    ['b', { version: '2.0.0' }],
    ['d', { version: '4.0.0' }],
  ]);
  const diff = diffLockfiles(before, after);
  assert.strictEqual(diff.added.length, 1);
  assert.strictEqual(diff.removed.length, 1);
  assert.strictEqual(diff.changed.length, 1);
  assert.strictEqual(diff.unchanged.length, 1);
  assert.strictEqual(diff.added[0].name, 'd');
  assert.strictEqual(diff.removed[0].name, 'c');
  assert.strictEqual(diff.changed[0].name, 'a');
  assert.strictEqual(diff.unchanged[0].name, 'b');
});

test('diffLockfiles: empty maps', () => {
  const diff = diffLockfiles(new Map(), new Map());
  assert.strictEqual(diff.added.length, 0);
  assert.strictEqual(diff.removed.length, 0);
  assert.strictEqual(diff.changed.length, 0);
  assert.strictEqual(diff.unchanged.length, 0);
});

test('diffLockfiles: sorted output', () => {
  const before = new Map();
  const after = new Map([
    ['zebra', { version: '1.0.0' }],
    ['apple', { version: '2.0.0' }],
    ['mango', { version: '3.0.0' }],
  ]);
  const diff = diffLockfiles(before, after);
  assert.strictEqual(diff.added[0].name, 'apple');
  assert.strictEqual(diff.added[1].name, 'mango');
  assert.strictEqual(diff.added[2].name, 'zebra');
});

// ── classifyVersionChange ───────────────────────────────

test('classifyVersionChange: major', () => {
  assert.strictEqual(classifyVersionChange('1.0.0', '2.0.0'), 'major');
});

test('classifyVersionChange: minor', () => {
  assert.strictEqual(classifyVersionChange('1.0.0', '1.1.0'), 'minor');
});

test('classifyVersionChange: patch', () => {
  assert.strictEqual(classifyVersionChange('1.0.0', '1.0.1'), 'patch');
});

test('classifyVersionChange: prerelease', () => {
  assert.strictEqual(classifyVersionChange('1.0.0', '1.0.0-beta.1'), 'prerelease');
});

test('classifyVersionChange: unknown for non-semver', () => {
  assert.strictEqual(classifyVersionChange('latest', '1.0.0'), 'unknown');
});

// ── computeStats ────────────────────────────────────────

test('computeStats: basic', () => {
  const diff = {
    added: [{ name: 'a', version: '1.0.0' }],
    removed: [{ name: 'b', version: '2.0.0' }],
    changed: [
      { name: 'c', before: '1.0.0', after: '1.1.0' },
      { name: 'd', before: '1.0.0', after: '2.0.0' },
    ],
    unchanged: [{ name: 'e', version: '5.0.0' }],
  };
  const stats = computeStats(diff);
  assert.strictEqual(stats.added, 1);
  assert.strictEqual(stats.removed, 1);
  assert.strictEqual(stats.changed, 2);
  assert.strictEqual(stats.unchanged, 1);
  assert.strictEqual(stats.total, 5);
  assert.strictEqual(stats.changeTypes.minor, 1);
  assert.strictEqual(stats.changeTypes.major, 1);
});

test('computeStats: empty diff', () => {
  const stats = computeStats({ added: [], removed: [], changed: [], unchanged: [] });
  assert.strictEqual(stats.total, 0);
});

// ── Integration: parse + diff ───────────────────────────

test('integration: npm lockfile full flow', () => {
  const before = JSON.stringify({
    lockfileVersion: 3,
    packages: {
      '': {},
      'node_modules/lodash': { version: '4.17.20' },
      'node_modules/express': { version: '4.17.0' },
    },
  });
  const after = JSON.stringify({
    lockfileVersion: 3,
    packages: {
      '': {},
      'node_modules/lodash': { version: '4.17.21' },
      'node_modules/mocha': { version: '10.0.0' },
    },
  });
  const beforeMap = parseLockfile(before, 'npm');
  const afterMap = parseLockfile(after, 'npm');
  const diff = diffLockfiles(beforeMap, afterMap);
  assert.strictEqual(diff.changed.length, 1);
  assert.strictEqual(diff.added.length, 1);
  assert.strictEqual(diff.removed.length, 1);
  assert.strictEqual(diff.changed[0].name, 'lodash');
  assert.strictEqual(diff.added[0].name, 'mocha');
  assert.strictEqual(diff.removed[0].name, 'express');
});

// ── pnpm peer dep annotations ─────────────────────────

test('parsePnpmLock: peer dep annotation stripped', () => {
  const content = `lockfileVersion: '9.0'

packages:

  /@babel/core@7.20.0(react@18.2.0):
    resolution: {tarball: '...'}

  /lodash@4.17.21:
    resolution: {tarball: '...'}
`;
  const pkgs = parsePnpmLock(content);
  assert.strictEqual(pkgs.get('@babel/core').version, '7.20.0');
  assert.strictEqual(pkgs.get('lodash').version, '4.17.21');
});

test('parsePnpmLock: scoped package with peer deps', () => {
  const content = `lockfileVersion: '9.0'

packages:

  /@types/react@18.2.0:
    resolution: {tarball: '...'}

  /@types/react-dom@18.2.0(@types/react@18.2.0):
    resolution: {tarball: '...'}
`;
  const pkgs = parsePnpmLock(content);
  assert.strictEqual(pkgs.get('@types/react').version, '18.2.0');
  assert.strictEqual(pkgs.get('@types/react-dom').version, '18.2.0');
});

// ── classifyVersionChange: edge cases ───────────────────

test('classifyVersionChange: same version is unknown', () => {
  assert.strictEqual(classifyVersionChange('1.0.0', '1.0.0'), 'unknown');
});

test('classifyVersionChange: prerelease to stable', () => {
  assert.strictEqual(classifyVersionChange('1.0.0-beta.1', '1.0.0'), 'prerelease');
});

test('classifyVersionChange: build metadata stripped', () => {
  assert.strictEqual(classifyVersionChange('1.0.0+build123', '1.0.1'), 'patch');
});

// ── diffLockfiles: edge cases ───────────────────────────

test('diffLockfiles: all removed', () => {
  const before = new Map([
    ['a', { version: '1.0.0' }],
    ['b', { version: '2.0.0' }],
  ]);
  const after = new Map();
  const diff = diffLockfiles(before, after);
  assert.strictEqual(diff.removed.length, 2);
  assert.strictEqual(diff.added.length, 0);
});

test('diffLockfiles: all added', () => {
  const before = new Map();
  const after = new Map([
    ['a', { version: '1.0.0' }],
    ['b', { version: '2.0.0' }],
  ]);
  const diff = diffLockfiles(before, after);
  assert.strictEqual(diff.added.length, 2);
  assert.strictEqual(diff.removed.length, 0);
});

// ── computeStats: changeTypes edge ──────────────────────

test('computeStats: all prerelease changes', () => {
  const diff = {
    added: [],
    removed: [],
    changed: [{ name: 'a', before: '1.0.0', after: '1.0.0-beta.2' }],
    unchanged: [],
  };
  const stats = computeStats(diff);
  assert.strictEqual(stats.changeTypes.prerelease, 1);
});

// ── detectFormat: edge cases ────────────────────────────

test('detectFormat: npm by packages field in content', () => {
  const content = JSON.stringify({ packages: { 'node_modules/foo': { version: '1.0.0' } } });
  assert.strictEqual(detectFormat('unknown.txt', content), 'npm');
});

test('detectFormat: npm by dependencies field in content', () => {
  const content = JSON.stringify({ dependencies: { foo: { version: '1.0.0' } } });
  assert.strictEqual(detectFormat('unknown.txt', content), 'npm');
});

test('detectFormat: empty content returns null', () => {
  assert.strictEqual(detectFormat('file.txt', ''), null);
});

// ── parseYarnLock: edge cases ───────────────────────────

test('parseYarnLock: empty content', () => {
  const pkgs = parseYarnLock('');
  assert.strictEqual(pkgs.size, 0);
});

test('parseYarnLock: comments only', () => {
  const pkgs = parseYarnLock('# This is a comment\n# Another comment\n');
  assert.strictEqual(pkgs.size, 0);
});

test('parseYarnLock: entry with no version skipped', () => {
  const content = `lodash@^4.17.0:
  resolved "..."

express@^4.18.0:
  version "4.18.2"
`;
  const pkgs = parseYarnLock(content);
  assert.strictEqual(pkgs.size, 1);
  assert.strictEqual(pkgs.get('express').version, '4.18.2');
});

// ── parsePackageLock: edge cases ────────────────────────

test('parsePackageLock: v1 deeply nested', () => {
  const lock = JSON.stringify({
    lockfileVersion: 1,
    dependencies: {
      a: {
        version: '1.0.0',
        dependencies: {
          b: {
            version: '2.0.0',
            dependencies: {
              c: { version: '3.0.0' },
            },
          },
        },
      },
    },
  });
  const pkgs = parsePackageLock(lock);
  assert.strictEqual(pkgs.size, 3);
  assert.strictEqual(pkgs.get('c').version, '3.0.0');
});

test('parsePackageLock: empty packages object', () => {
  const lock = JSON.stringify({ lockfileVersion: 3, packages: {} });
  const pkgs = parsePackageLock(lock);
  assert.strictEqual(pkgs.size, 0);
});

// ── parseYarnLock: branch coverage edge cases ─────────

test('parseYarnLock: tab-indented version line', () => {
  const content = 'lodash@^4.17.0:\n\tversion "4.17.21"\n';
  const pkgs = parseYarnLock(content);
  assert.strictEqual(pkgs.get('lodash').version, '4.17.21');
});

test('parseYarnLock: empty line before version breaks lookahead', () => {
  const content = 'lodash@^4.17.0:\n\n  version "4.17.21"\n';
  const pkgs = parseYarnLock(content);
  assert.strictEqual(pkgs.has('lodash'), false);
});

test('parseYarnLock: yarn berry __metadata header', () => {
  const content = '__metadata:\n  version: 8\n\nlodash@^4.17.0:\n  version "4.17.21"\n  resolution: "lodash@npm:4.17.21"\n';
  const pkgs = parseYarnLock(content);
  assert.strictEqual(pkgs.get('lodash').version, '4.17.21');
});

test('parseYarnLock: key with trailing spaces before colon', () => {
  const content = 'lodash@^4.17.0   :\n  version "4.17.21"\n';
  const pkgs = parseYarnLock(content);
  assert.strictEqual(pkgs.get('lodash').version, '4.17.21');
});

// ── extractYarnPkgName: edge cases ─────────────────────

test('extractYarnPkgName: bare @ entry returns as-is', () => {
  // Entry that starts with @ but has no second @ (malformed) — defensive fallback
  assert.strictEqual(extractYarnPkgName('@'), '@');
});

// ── detectFormat: yarn berry content sniffing ──────────

test('detectFormat: yarn berry by __metadata header', () => {
  const content = '__metadata:\n  version: 8\n';
  assert.strictEqual(detectFormat('unknown.txt', content), 'yarn');
});

test('detectFormat: yarn berry by resolution pattern', () => {
  const content = 'lodash@^4.17.0:\n  resolution: "lodash@npm:4.17.21"\n';
  assert.strictEqual(detectFormat('unknown.txt', content), 'yarn');
});

// ── parsePackageLock: v1 with dependencies has version ──

test('parsePackageLock: v1 entry without version skipped', () => {
  const lock = JSON.stringify({
    lockfileVersion: 1,
    dependencies: {
      badpkg: { /* no version */ },
      goodpkg: { version: '1.0.0' },
    },
  });
  const pkgs = parsePackageLock(lock);
  assert.strictEqual(pkgs.size, 1);
  assert.strictEqual(pkgs.get('goodpkg').version, '1.0.0');
});

// ────────────────────────────────────────────────────────

console.log(`\n\n${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
